language: julia
os:
    - linux
julia:
    - 1.1
#     - nightly
notifications:
  email: false
before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia -e 'using Pkg; Pkg.build(PackageSpec(url="https://github.com/ivanslapnicar/Arrowhead.jl", rev="v1.1");verbose=true); Pkg.test("Arrowhead.jl",coverage=true)'
